apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbdata-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"  # Change this path if needed
  storageClassName: manual  # Added storage class for PVC binding

